### ISSUE TITLE
Add a cv like webpage || For my community members

### ISSUE THREAD

**Issue by sarthak49** [sarthak49/Personal_showcase#1]
### It is a one-page website add {logo, about section, Resume, work experiences, project, contact} add for just a template time like anyone add our personal details 
**using (Html,CSS and javascript) only** _Leave a comment if you can do_
`you can see for references`

**Comment by vishal1patidar** [comment]
**I will do please assign me**༼ つ ◕_◕ ༽つ

**Comment by sarthak49** [comment]
### thank you for contributing

**Comment by vishal1patidar** [comment]
### Thankx for merging my request @sarthak49  
**Happy new year**
